### ISSUE TITLE
Move into k8s

### ISSUE THREAD

**Issue by ajkiessl** [psu-libraries/fams_tools#32]
FAMS Tools is currently running on a CentOS server in production (rubytools.vmhost.psu.edu).  This is getting old and more difficult to maintain.  It would probably be a good idea to start thinking about moving this into the k8s infrastructure.

Things we'd have to consider:

- Mysql database
- File stores
- Removing capistrano
- What to do with the rubytools app and retiring the rubytools server
- It's already containerized although we may want to use a different base image
- Hook up CD

**Comment by whereismyjetpack** [comment]
@ajkiessl , I started looking into this, and have a few questions, is `/public` the only filestore that it uses?

**Comment by ajkiessl** [comment]
@whereismyjetpack Yeah, that should be it.  Sometimes files are temporarily stored in `app/parsing_files`, but only during imports and any of the features that require a file upload.  The files are only needed for the duration of the import/processing.

**Comment by ajkiessl** [comment]
This is done
